"""Add employee_id to quest_assignments

Revision ID: dfd12d12870c
Revises: 62f4e26f1b2a
Create Date: 2025-05-23 15:34:41.230790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfd12d12870c'
down_revision: Union[str, None] = '62f4e26f1b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.drop_table('tasks')
    op.add_column('quest_assignments', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.alter_column('quest_assignments', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('quest_assignments_user_id_fkey', 'quest_assignments', type_='foreignkey')
    op.drop_constraint('quest_assignments_template_id_fkey', 'quest_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'quest_assignments', 'employee_profiles', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'quest_assignments', 'quest_templates', ['template_id'], ['id'])
    op.drop_column('quest_assignments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_assignments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quest_assignments', type_='foreignkey')
    op.drop_constraint(None, 'quest_assignments', type_='foreignkey')
    op.create_foreign_key('quest_assignments_template_id_fkey', 'quest_assignments', 'quest_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('quest_assignments_user_id_fkey', 'quest_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('quest_assignments', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('quest_assignments', 'employee_id')
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name='tasks_assigned_by_id_fkey'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name='tasks_assigned_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evaluator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name='evaluations_employee_id_fkey'),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], name='evaluations_evaluator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='evaluations_pkey')
    )
    # ### end Alembic commands ###
